### PR TITLE
add checksums for win32-ARM64 (#15)

### PR DESCRIPTION
**Pull request by Mateusz-Grzelinski**
a PR for running integration pipeline

### CODE REVIEW

**Comment by Mateusz-Grzelinski** [comment]
@ptc-jhoerner please check if this command will work - I have no way of testing arm64 system: 
```sh
pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ actionlint-py==1.6.25.9.dev5
```

**Comment by ptc-jhoerner** [comment]
This works fine on ARM64 Windows, the wheel was built and installed fine via that pip command.

**Comment by Mateusz-Grzelinski** [comment]
@ptc-jhoerner  now version 1.6.25 and 1.6.26 are available with win arm64 support

**Comment by ptc-jhoerner** [comment]
Thanks, great!

**Pull request merged**
